name: 'TypeScript Typecheck'

on: [push, pull_request]

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: TypeScript report
        uses: fersilva16/ts-report-action@1.2.1
